import type { Metadata } from "next";
// TEMPORARILY DISABLED - Waiting for Stack Auth keys
// import { StackProvider, StackTheme } from "@stackframe/stack";
// import { stackClientApp } from "../stack/client";
import { MathJaxContext } from "better-react-mathjax";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const mathJaxConfig = {
    tex: {
        inlineMath: [
            ["$", "$"],
            ["\\(", "\\)"],
        ],
        displayMath: [
            ["$$", "$$"],
            ["\\[", "\\]"],
        ],
        processEscapes: true,
        processEnvironments: true,
    },
    svg: {
        fontCache: "global",
    },
    options: {
        skipHtmlTags: ["script", "noscript", "style", "textarea", "pre"],
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <MathJaxContext config={mathJaxConfig}>
                    {/* TEMPORARILY DISABLED - Waiting for Stack Auth keys */}
                    {/* <StackProvider app={stackClientApp}><StackTheme> */}
                    {children}
                    {/* </StackTheme></StackProvider> */}
                </MathJaxContext>
            </body>
        </html>
    );
}
